name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test run
        uses: ./
        with:
          subcommand: update-conda-envs
          args: ".test/*.yaml .test/*.yaml"
